# Generated by Django 5.0.1 on 2024-02-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_room_options_room_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participant',
            field=models.ManyToManyField(related_name='participants', to='baseapp.topic'),
        ),
    ]
