# Generated by Django 5.0.1 on 2024-02-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_alter_room_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
